-- -----------------------------------------
-- TABELA 1: USUARIO
-- -----------------------------------------
CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    perfil VARCHAR2(20) NOT NULL,
    cargo VARCHAR2(50),
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT chk_usuario_perfil CHECK (perfil IN ('ADMINISTRADOR', 'PROFESSOR', 'RESPONSAVEL')),
    CONSTRAINT chk_usuario_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE USUARIO IS 'Usuários do sistema (Administrador, Professor, Responsável)';
COMMENT ON COLUMN USUARIO.CARGO IS 'Cargo (apenas para perfil ADMINISTRADOR)';

-- -----------------------------------------
-- TABELA 2: PROFESSOR
-- -----------------------------------------
CREATE TABLE PROFESSOR (
    id_professor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL UNIQUE,
    matricula VARCHAR2(20) NOT NULL UNIQUE,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_prof_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
    CONSTRAINT chk_prof_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE PROFESSOR IS 'Dados específicos dos professores';

-- -----------------------------------------
-- TABELA 3: RESPONSAVEL
-- -----------------------------------------
CREATE TABLE RESPONSAVEL (
    id_responsavel NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL UNIQUE,
    cpf VARCHAR2(14) NOT NULL UNIQUE,
    telefone VARCHAR2(20),
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_resp_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
    CONSTRAINT chk_resp_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE RESPONSAVEL IS 'Dados específicos dos responsáveis';

-- ==========================================
-- NÚCLEO B: ESTRUTURA ESCOLAR
-- ==========================================

-- -----------------------------------------
-- TABELA 4: DISCIPLINA
-- -----------------------------------------
CREATE TABLE DISCIPLINA (
    id_disciplina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    area VARCHAR2(50),
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT chk_disc_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE DISCIPLINA IS 'Disciplinas acadêmicas';
COMMENT ON COLUMN DISCIPLINA.AREA IS 'Área do conhecimento (Exatas, Humanas, etc.)';

-- -----------------------------------------
-- TABELA 5: TURMA
-- -----------------------------------------
CREATE TABLE TURMA (
    id_turma NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    ano_letivo NUMBER(4) NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT uk_turma UNIQUE (nome, ano_letivo),
    CONSTRAINT chk_turma_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE TURMA IS 'Turmas da escola';

-- -----------------------------------------
-- TABELA 6: ALUNO
-- -----------------------------------------
CREATE TABLE ALUNO (
    id_aluno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    matricula VARCHAR2(20) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    id_turma NUMBER NOT NULL,
    ano_letivo NUMBER(4) NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_aluno_turma FOREIGN KEY (id_turma) REFERENCES TURMA(id_turma),
    CONSTRAINT chk_aluno_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE ALUNO IS 'Dados dos alunos';
COMMENT ON COLUMN ALUNO.ID_TURMA IS 'Turma atual do aluno';
COMMENT ON COLUMN ALUNO.ANO_LETIVO IS 'Ano letivo atual do aluno';

-- -----------------------------------------
-- TABELA 7: ALUNO_RESPONSAVEL 
-- -----------------------------------------
CREATE TABLE ALUNO_RESPONSAVEL (
    id_aluno NUMBER NOT NULL,
    id_responsavel NUMBER NOT NULL,
    parentesco VARCHAR2(30) NOT NULL,
    principal NUMBER(1) DEFAULT 0 NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    PRIMARY KEY (id_aluno, id_responsavel),
    CONSTRAINT fk_aresp_aluno FOREIGN KEY (id_aluno) REFERENCES ALUNO(id_aluno),
    CONSTRAINT fk_aresp_responsavel FOREIGN KEY (id_responsavel) REFERENCES RESPONSAVEL(id_responsavel),
    CONSTRAINT chk_aresp_principal CHECK (principal IN (0, 1)),
    CONSTRAINT chk_aresp_ativo CHECK (ativo IN (0, 1)),
    CONSTRAINT chk_aresp_parentesco CHECK (parentesco IN ('PAI', 'MAE', 'AVO', 'AVOH', 'TIO', 'TIA', 'OUTRO'))
);

COMMENT ON TABLE ALUNO_RESPONSAVEL IS 'Vínculo N:N entre alunos e responsáveis';

-- -----------------------------------------
-- TABELA 8: VINCULO_PROFESSOR
-- -----------------------------------------
CREATE TABLE VINCULO_PROFESSOR (
    id_vinculo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_turma NUMBER NOT NULL,
    id_disciplina NUMBER NOT NULL,
    id_professor NUMBER NOT NULL,
    ano_letivo NUMBER(4) NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    CONSTRAINT fk_vprof_turma FOREIGN KEY (id_turma) REFERENCES TURMA(id_turma),
    CONSTRAINT fk_vprof_disciplina FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id_disciplina),
    CONSTRAINT fk_vprof_professor FOREIGN KEY (id_professor) REFERENCES PROFESSOR(id_professor),
    CONSTRAINT chk_vprof_ativo CHECK (ativo IN (0, 1)),
    CONSTRAINT uk_vinculo UNIQUE (id_turma, id_disciplina, id_professor, ano_letivo)
);

COMMENT ON TABLE VINCULO_PROFESSOR IS 'Vínculo entre professor, turma e disciplina';

-- ==========================================
-- NÚCLEO C: ACOMPANHAMENTO E TAGS
-- ==========================================

-- -----------------------------------------
-- TABELA 9: BIMESTRE
-- -----------------------------------------
CREATE TABLE BIMESTRE (
    id_bimestre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero NUMBER(1) NOT NULL,
    ano_letivo NUMBER(4) NOT NULL,
    dt_abertura DATE,
    dt_encerramento DATE,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    CONSTRAINT uk_bimestre UNIQUE (numero, ano_letivo),
    CONSTRAINT chk_numero_bimestre CHECK (numero BETWEEN 1 AND 4),
    CONSTRAINT chk_bimestre_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE BIMESTRE IS 'Períodos de abertura e encerramento dos bimestres';

-- -----------------------------------------
-- TABELA 10: TAG
-- -----------------------------------------
CREATE TABLE TAG (
    id_tag NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    cor VARCHAR2(7) DEFAULT '#000000',
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    CONSTRAINT uk_tag_nome UNIQUE (nome),
    CONSTRAINT chk_tag_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE TAG IS 'Tags para classificação de acompanhamentos';

-- -----------------------------------------
-- TABELA 11: ACOMPANHAMENTO
-- Contém a NOTA (media) e o FEEDBACK (descricao)
-- -----------------------------------------
CREATE TABLE ACOMPANHAMENTO (
    id_acompanhamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aluno NUMBER NOT NULL,
    id_vinculo NUMBER NOT NULL,
    id_bimestre NUMBER NOT NULL,
    descricao CLOB,
    media NUMBER(5,2),
    status VARCHAR2(25) DEFAULT 'RASCUNHO' NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_criacao DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_acomp_aluno FOREIGN KEY (id_aluno) REFERENCES ALUNO(id_aluno),
    CONSTRAINT fk_acomp_vinculo FOREIGN KEY (id_vinculo) REFERENCES VINCULO_PROFESSOR(id_vinculo),
    CONSTRAINT fk_acomp_bimestre FOREIGN KEY (id_bimestre) REFERENCES BIMESTRE(id_bimestre),
    CONSTRAINT uk_acompanhamento UNIQUE (id_aluno, id_vinculo, id_bimestre),
    CONSTRAINT chk_acomp_media CHECK (media BETWEEN 0 AND 10),
    CONSTRAINT chk_acomp_status CHECK (status IN (
        'RASCUNHO',
        'ENVIADO_PARA_REVISAO',
        'EM_REVISAO',
        'PUBLICADO',
        'DEVOLVIDO',
        'CANCELADO'
    )),
    CONSTRAINT chk_acomp_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE ACOMPANHAMENTO IS 'Registro bimestral do desenvolvimento do aluno';
COMMENT ON COLUMN ACOMPANHAMENTO.MEDIA IS 'Nota do aluno no bimestre (0 a 10)';
COMMENT ON COLUMN ACOMPANHAMENTO.DESCRICAO IS 'Feedback qualitativo do professor';

-- -----------------------------------------
-- TABELA 12: ACOMPANHAMENTO_TAG (N:N)
-- -----------------------------------------
CREATE TABLE ACOMPANHAMENTO_TAG (
    id_acompanhamento NUMBER NOT NULL,
    id_tag NUMBER NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    PRIMARY KEY (id_acompanhamento, id_tag),
    CONSTRAINT fk_atag_acompanhamento FOREIGN KEY (id_acompanhamento) REFERENCES ACOMPANHAMENTO(id_acompanhamento) ON DELETE CASCADE,
    CONSTRAINT fk_atag_tag FOREIGN KEY (id_tag) REFERENCES TAG(id_tag) ON DELETE CASCADE,
    CONSTRAINT chk_atag_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE ACOMPANHAMENTO_TAG IS 'Vínculo N:N entre acompanhamentos e tags';

-- ==========================================
-- NÚCLEO D: AUDITORIA E RETORNO
-- ==========================================

-- -----------------------------------------
-- TABELA 13: HISTORICO_AUDITORIA
-- -----------------------------------------
CREATE TABLE HISTORICO_AUDITORIA (
    id_historico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_acompanhamento NUMBER NOT NULL,
    id_usuario_acao NUMBER NOT NULL,
    estado_anterior VARCHAR2(50),
    estado_posterior VARCHAR2(50),
    dt_alteracao DATE DEFAULT SYSDATE,
    observacao VARCHAR2(4000),
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_hist_acompanhamento FOREIGN KEY (id_acompanhamento) REFERENCES ACOMPANHAMENTO(id_acompanhamento),
    CONSTRAINT fk_hist_usuario FOREIGN KEY (id_usuario_acao) REFERENCES USUARIO(id_usuario),
    CONSTRAINT chk_hist_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE HISTORICO_AUDITORIA IS 'Histórico de ações para auditoria';

-- -----------------------------------------
-- TABELA 14: RETORNO_RESPONSAVEL
-- -----------------------------------------
CREATE TABLE RETORNO_RESPONSAVEL (
    id_retorno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_acompanhamento NUMBER NOT NULL,
    id_responsavel NUMBER NOT NULL,
    ciencia NUMBER(1) DEFAULT 0 NOT NULL,
    dt_ciencia DATE,
    observacao VARCHAR2(4000),
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    CONSTRAINT fk_ret_acompanhamento FOREIGN KEY (id_acompanhamento) REFERENCES ACOMPANHAMENTO(id_acompanhamento),
    CONSTRAINT fk_ret_responsavel FOREIGN KEY (id_responsavel) REFERENCES RESPONSAVEL(id_responsavel),
    CONSTRAINT chk_ret_ciencia CHECK (ciencia IN (0, 1)),
    CONSTRAINT chk_ret_ativo CHECK (ativo IN (0, 1))
);

COMMENT ON TABLE RETORNO_RESPONSAVEL IS 'Ciência e observação do responsável';

-- ==========================================
-- ÍNDICES
-- ==========================================

-- USUARIO
CREATE INDEX idx_usuario_perfil ON USUARIO(perfil);

-- ALUNO
CREATE INDEX idx_aluno_nome ON ALUNO(nome);
CREATE INDEX idx_aluno_turma ON ALUNO(id_turma, ano_letivo);

-- ALUNO_RESPONSAVEL
CREATE INDEX idx_aluno_responsavel_resp ON ALUNO_RESPONSAVEL(id_responsavel);

-- VINCULO_PROFESSOR
CREATE INDEX idx_vinculo_professor ON VINCULO_PROFESSOR(id_professor);
CREATE INDEX idx_vinculo_turma ON VINCULO_PROFESSOR(id_turma);
CREATE INDEX idx_vinculo_disciplina ON VINCULO_PROFESSOR(id_disciplina);

-- ACOMPANHAMENTO
CREATE INDEX idx_acompanhamento_aluno ON ACOMPANHAMENTO(id_aluno);
CREATE INDEX idx_acompanhamento_bimestre ON ACOMPANHAMENTO(id_bimestre);
CREATE INDEX idx_acompanhamento_vinculo ON ACOMPANHAMENTO(id_vinculo);
CREATE INDEX idx_acompanhamento_status ON ACOMPANHAMENTO(status);
CREATE INDEX idx_acompanhamento_alu_bim ON ACOMPANHAMENTO(id_aluno, id_bimestre);

-- HISTORICO_AUDITORIA
CREATE INDEX idx_historico_acomp ON HISTORICO_AUDITORIA(id_acompanhamento);
CREATE INDEX idx_historico_usuario ON HISTORICO_AUDITORIA(id_usuario_acao);

-- RETORNO_RESPONSAVEL
CREATE INDEX idx_retorno_acomp ON RETORNO_RESPONSAVEL(id_acompanhamento);
CREATE INDEX idx_retorno_responsavel ON RETORNO_RESPONSAVEL(id_responsavel);

-- BIMESTRE
CREATE INDEX idx_bimestre_ano ON BIMESTRE(ano_letivo);